# /src/my_robot_bringup/config/ekf.yaml

ekf_filter_node:
  ros__parameters:
    # GENERAL PARAMETERS
    frequency: 30.0
    two_d_mode: true
    publish_tf: true

    # FRAME PARAMETERS
    map_frame: map                # Not used in this config, but good practice to define
    odom_frame: odom              # The frame for odometry
    base_link_frame: base_footprint # The robot's base frame
    world_frame: odom             # IMPORTANT: For continuous odometry, world_frame is odom

    # ODOMETRY INPUT
    # The topic name here ('/odom') MUST match the remapped output of your odometry bridge.
    odom0: /odom
    
    # [X, Y, Z, roll, pitch, yaw, Vx, Vy, Vz, Vroll, Vpitch, Vyaw, Ax, Ay, Az]
    # We are fusing X and Y velocity, and Yaw velocity from the Gazebo DiffDrive plugin.
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  false,
                   false, false, true,
                   false, false, false]
    
    odom0_queue_size: 10
    odom0_nodelay: true
    odom0_differential: false
    odom0_relative: false